name: Build Commit

on:
  push:
    branches:
      - master
    paths:
      - cmd/**
      - internal/**
      - pkg/**
      - go.mod
      - go.sum
      - .github/workflows/build.yml

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: windows-amd64
            runner: windows-latest
            goos: windows
            goarch: amd64
            goarm: ""
          - name: linux-amd64
            runner: ubuntu-latest
            goos: linux
            goarch: amd64
            goarm: ""
          - name: linux-armv7
            runner: ubuntu-latest
            goos: linux
            goarch: arm
            goarm: "7"
          - name: linux-arm64
            runner: ubuntu-latest
            goos: linux
            goarch: arm64
            goarm: ""
          - name: mac-amd64
            runner: macos-latest
            goos: darwin
            goarch: amd64
            goarm: ""
          - name: mac-arm64
            runner: macos-latest
            goos: darwin
            goarch: arm64
            goarm: ""
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Cache Go modules and build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}-

      - name: Build
        shell: bash
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: |
          mkdir -p dist
          if [ "$GOOS" = "windows" ]; then
            ext=".exe"
          else
            ext=""
          fi
          go build -v -o dist/${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}$ext cmd/romm-hash-matcher/main.go
      - name: Upload Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist/${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}*
